### ISSUE TITLE
QTR Tool failing when reducing the ignore list for the following benchmarks: avrora, xalan

### ISSUE THREAD

**Issue by greatmazinger** [RedlineResearch/QTR-tool#10]
The following exception occurs when running **xalan** using the following command:

`java -javaagent:./instrumenter-1.0-SNAPSHOT-jar-with-dependencies.jar -jar /path/to/dacapo-9.12-bach.jar --no-validation -t 1 xalan`

`Exception in thread "main" java.lang.NoSuchMethodError: java/util/Locale.<init>(Lsun/util/locale/BaseLocale;Lsun/util/locale/LocaleExtensions;Ljavassist/runtime/Inner;)V (loaded from jrt:/java.base by <Bootstrap Loader>) called from class java.util.Locale$Cache (loaded from jrt:/java.base by <Bootstrap Loader>).                                                                   
    at java.base/java.util.Locale$Cache.createObject(Locale.java:857)                                                                                                                         
    at java.base/java.util.Locale$Cache.createObject(Locale.java:847)                                                                                                                         
    at java.base/sun.util.locale.LocaleObjectCache.get(LocaleObjectCache.java:61)                                                                                                             
    at java.base/java.util.Locale.getInstance(Locale.java:840)                                                                                                                                
    at java.base/java.util.Locale.forLanguageTag(Locale.java:1725)                                                                                                                            
    at java.base/sun.util.cldr.CLDRBaseLocaleDataMetaInfo.<clinit>(CLDRBaseLocaleDataMetaInfo.java:41)                                                                                        
    at java.base/sun.util.cldr.CLDRLocaleProviderAdapter.<clinit>(CLDRLocaleProviderAdapter.java:62)                                                                                          
    at java.base/java.lang.Class.forNameImpl(Native Method)                                                                                                                                   
    at java.base/java.lang.Class.forName(Class.java:347)                                                                                                                                      
    at java.base/sun.util.locale.provider.LocaleProviderAdapter.forType(LocaleProviderAdapter.java:176)                                                                                       
    at java.base/sun.util.locale.provider.LocaleProviderAdapter.findAdapter(LocaleProviderAdapter.java:279)                                                                                   
    at java.base/sun.util.locale.provider.LocaleProviderAdapter.getAdapter(LocaleProviderAdapter.java:250)                                                                                    
    at java.base/java.text.DecimalFormat.<init>(DecimalFormat.java:404)                                                                                                                       
    at org.dacapo.harness.TestHarness.twoDecimalPlaces(TestHarness.java:234)                                                                                                                  
    at org.dacapo.harness.TestHarness.<clinit>(TestHarness.java:48)                                                                                                                           
    at Harness.main(Harness.java:17)`

**Comment by greatmazinger** [comment]
The following exception happens for **avrora**:

`Exception in thread "main" java.lang.NoSuchMethodError: java/util/Locale.<init>(Lsun/util/locale/BaseLocale;Lsun/util/locale/LocaleExtensions;Ljavassist/runtime/Inner;)V (loaded from jrt:/java.base by <Bootstrap Loader>) called from class java.util.Locale$Cache (loaded from jrt:/java.base by <Bootstrap Loader>).                                                                   
    at java.base/java.util.Locale$Cache.createObject(Locale.java:857)                                                                                                                         
    at java.base/java.util.Locale$Cache.createObject(Locale.java:847)                                                                                                                         
    at java.base/sun.util.locale.LocaleObjectCache.get(LocaleObjectCache.java:61)                                                                                                             
    at java.base/java.util.Locale.getInstance(Locale.java:840)                                                                                                                                
    at java.base/java.util.Locale.forLanguageTag(Locale.java:1725)                                                                                                                            
    at java.base/sun.util.cldr.CLDRBaseLocaleDataMetaInfo.<clinit>(CLDRBaseLocaleDataMetaInfo.java:41)                                                                                        
    at java.base/sun.util.cldr.CLDRLocaleProviderAdapter.<clinit>(CLDRLocaleProviderAdapter.java:62)                                                                                          
    at java.base/java.lang.Class.forNameImpl(Native Method)                                                                                                                                   
    at java.base/java.lang.Class.forName(Class.java:347)                                                                                                                                      
    at java.base/sun.util.locale.provider.LocaleProviderAdapter.forType(LocaleProviderAdapter.java:176)                                                                                       
    at java.base/sun.util.locale.provider.LocaleProviderAdapter.findAdapter(LocaleProviderAdapter.java:279)                                                                                   
    at java.base/sun.util.locale.provider.LocaleProviderAdapter.getAdapter(LocaleProviderAdapter.java:250)                                                                                    
    at java.base/java.text.DecimalFormat.<init>(DecimalFormat.java:404)                                                                                                                       
    at org.dacapo.harness.TestHarness.twoDecimalPlaces(TestHarness.java:234)                                                                                                                  
    at org.dacapo.harness.TestHarness.<clinit>(TestHarness.java:48)                                                                                                                           
    at Harness.main(Harness.java:17)`

**Comment by greatmazinger** [comment]
The problem was that the DaCapo jar was compiled with an older version of Java (most probably 1.6 or 1.7). This causes a ClassNotFoundError when using anything even slightly modern (Java 11+).
So the solution for now is to use Java 1.8 to run the DaCapo benchmarks:

Works with Java Hotspot 1.8:

1. xalan

**Comment by greatmazinger** [comment]
Closing as using Java 8 is working.
