### ISSUE TITLE
h2 benchmark fails on OOM

### ISSUE THREAD

**Issue by greatmazinger** [RedlineResearch/QTR-tool#11]
`JVMDUMP039I Processing dump event "systhrow", detail "java/lang/OutOfMemoryError" at 2020/04/21 11:47:24 - please wait.
JVMDUMP032I JVM requested System dump using '/data/rveroy/pulsrc/qtrtool/java/h2-03/core.20200421.114724.12729.0001.dmp' in response to an event
JVMDUMP010I System dump written to /data/rveroy/pulsrc/qtrtool/java/h2-03/core.20200421.114724.12729.0001.dmp
JVMDUMP032I JVM requested Heap dump using '/data/rveroy/pulsrc/qtrtool/java/h2-03/heapdump.20200421.114724.12729.0002.phd' in response to an event
JVMDUMP010I Heap dump written to /data/rveroy/pulsrc/qtrtool/java/h2-03/heapdump.20200421.114724.12729.0002.phd
JVMDUMP032I JVM requested Java dump using '/data/rveroy/pulsrc/qtrtool/java/h2-03/javacore.20200421.114724.12729.0003.txt' in response to an event
JVMDUMP010I Java dump written to /data/rveroy/pulsrc/qtrtool/java/h2-03/javacore.20200421.114724.12729.0003.txt
JVMDUMP032I JVM requested Snap dump using '/data/rveroy/pulsrc/qtrtool/java/h2-03/Snap.20200421.114724.12729.0004.trc' in response to an event
JVMDUMP010I Snap dump written to /data/rveroy/pulsrc/qtrtool/java/h2-03/Snap.20200421.114724.12729.0004.trc
JVMDUMP013I Processed dump event "systhrow", detail "java/lang/OutOfMemoryError".
java.lang.reflect.InvocationTargetException
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.dacapo.harness.H2.preIteration(H2.java:77)
	at org.dacapo.harness.Benchmark.run(Benchmark.java:152)
	at org.dacapo.harness.TestHarness.runBenchmark(TestHarness.java:218)
	at org.dacapo.harness.TestHarness.main(TestHarness.java:171)
	at Harness.main(Harness.java:17)
Caused by: java.lang.OutOfMemoryError: Java heap space
	at java.util.HashMap.resize(HashMap.java:704)
	at java.util.HashMap.putVal(HashMap.java:663)
	at java.util.HashMap.put(HashMap.java:612)
	at java.util.Collections$SynchronizedMap.put(Collections.java:2590)
	at veroy.research.qtrtool.javassist.QTRProxy.getObjectId(QTRProxy.java:545)
	at veroy.research.qtrtool.javassist.QTRProxy.onObjectAlloc(QTRProxy.java:132)
	at org.h2.value.ValueTimestamp.getNoCopy(ValueTimestamp.java:140)
	at org.h2.value.ValueTimestamp.get(ValueTimestamp.java:129)
	at org.h2.jdbc.JdbcPreparedStatement.setTimestamp(JdbcPreparedStatement.java:389)
	at org.apache.derbyTesting.system.oe.load.SimpleInsert.orderTable(SimpleInsert.java:428)
	at org.apache.derbyTesting.system.oe.load.SimpleInsert.populateForOneWarehouse(SimpleInsert.java:149)
	at org.apache.derbyTesting.system.oe.load.SimpleInsert.populateAllTables(SimpleInsert.java:127)
	at org.apache.derbyTesting.system.oe.load.ThreadInsert.populateAllTables(ThreadInsert.java:127)
	at org.dacapo.h2.TPCC.loadData(TPCC.java:400)
	at org.dacapo.h2.TPCC.preIterationMemoryDB(TPCC.java:215)
	at org.dacapo.h2.TPCC.preIteration(TPCC.java:254)
	... 9 more
Exception in thread "Thread-0" java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1479)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1477)
	at veroy.research.qtrtool.javassist.MethodInstrumenter.writeWitnessMap(MethodInstrumenter.java:211)
	at veroy.research.qtrtool.javassist.MethodInstrumenter.writeMapsToFile(MethodInstrumenter.java:198)
	at veroy.research.qtrtool.javassist.DynamicInstrumenter$1.run(DynamicInstrumenter.java:61)
`

**Comment by greatmazinger** [comment]
Use a sufficiently large heap size: -Xms512m -Xmx4096m worked for me, but something smaller could probably work.
