### ISSUE TITLE
Error compiling 'insertBefore' code into class/method with no method body

### ISSUE THREAD

**Issue by greatmazinger** [RedlineResearch/QTR-tool#12]
`** NATIVE - java.lang.invoke.CatchHandle#numCatchTargetArgsToPassThrough                                                                                                                      
Error compiling 'insertBefore' code into class/method: numCatchTargetArgsToPassThrough ==? false                                                                                              
javassist.CannotCompileException: no method body                                                                                                                                              
    at javassist.CtBehavior.insertBefore(CtBehavior.java:776)                                                                                                                                 
    at javassist.CtBehavior.insertBefore(CtBehavior.java:766)                                                                                                                                 
    at veroy.research.qtrtool.javassist.MethodInstrumenter.instrumentMethods(MethodInstrumenter.java:159)                                                                                     
    at veroy.research.qtrtool.javassist.QtrToolTransformer.transform(QtrToolTransformer.java:41)                                                                                              
    at java.instrument/java.lang.instrument.ClassFileTransformer.transform(ClassFileTransformer.java:246)                                                                                     
    at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)                                                                                               
    at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:563)                                                                                             
    at java.base/java.lang.VMAccess.findClassOrNull(Native Method)                                                                                                                            
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1072)                                                                                                                       
    at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)                                                                                                  
    at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:167)                                                                                    
    at veroy.research.qtrtool.javassist.DynamicInstrumenter.premain(DynamicInstrumenter.java:87)                                                                                              
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)                                                                                                         
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)                                                                                       
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)                                                                               
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)                                                                                                                             
    at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:513)                                                                                
    at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:525)                                                                               
** NATIVE - java.lang.invoke.FinallyHandle#numFinallyTargetArgsToPassThrough                                                                                                                  
Error compiling 'insertBefore' code into class/method: numFinallyTargetArgsToPassThrough ==? false                                                                                            
javassist.CannotCompileException: no method body                                                                                                                                              
    at javassist.CtBehavior.insertBefore(CtBehavior.java:776)                                                                                                                                 
    at javassist.CtBehavior.insertBefore(CtBehavior.java:766)                                                                                                                                 
    at veroy.research.qtrtool.javassist.MethodInstrumenter.instrumentMethods(MethodInstrumenter.java:159)                                                                                     
    at veroy.research.qtrtool.javassist.QtrToolTransformer.transform(QtrToolTransformer.java:41)                                                                                              
    at java.instrument/java.lang.instrument.ClassFileTransformer.transform(ClassFileTransformer.java:246)                                                                                     
    at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)                                                                                               
    at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:563)                                                                                             
    at java.base/java.lang.VMAccess.findClassOrNull(Native Method)                                                                                                                            
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1072)                                                                                                                       
    at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)                                                                                                  
    at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:167)                                                                                    
    at veroy.research.qtrtool.javassist.DynamicInstrumenter.premain(DynamicInstrumenter.java:87)                                                                                              
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)                                                                                                         
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)                                                                                       
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)                                                                               
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)                                                                                                                             
    at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:513)                                                                                
    at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:525)`

**Comment by greatmazinger** [comment]
Fixed this in the [latest commit](https://github.com/RedlineResearch/QTR-tool/commit/43eaa7820673839fee659fd07cdb10ee09e80f0e) where the setBody call is uncommented from the debugging run.
