### ISSUE TITLE
Unexpected event code 0

### ISSUE THREAD

**Issue by greatmazinger** [RedlineResearch/QTR-tool#4]
`SHUTDOWN running.
Exception in thread "Thread-0" java.lang.IllegalStateException: Unexpected event: 0
        at veroy.research.qtrtool.javassist.QTRProxy.flushBuffer(QTRProxy.java:436)
        at veroy.research.qtrtool.javassist.DynamicInstrumenter$1.run(DynamicInstrumenter.java:60)`

**Comment by greatmazinger** [comment]
When flushing the buffer, Math.min should have been used instead of Math.max.
